### ISSUE TITLE
Error Downloading Data and Running Tutorial

### ISSUE THREAD

**Issue by kls2177** [tyfolino/climkern#14]
Hi Tyler,

   I have a Master's student who is going to be using your package. I have asked them to go through your tutorial and we are having some issues:

1. We are having trouble downloading the data. The `python -m climkern download` command is giving us a hash error 
![Error1](https://github.com/tyfolino/climkern/assets/13908222/3840be37-c61d-491b-8573-2078b161b3ef)

2. I manually downloaded data.zip from Zenodo and added to the package directory, but then I get an error when running the following line of code from the tutorial: `ck.calc_T_feedbacks(ctrl.T,ctrl.TS,ctrl.PS,pert.T,pert.TS,pert.PS,pert.TROP_P,kern="GFDL")`  
<img width="1017" alt="Error2" src="https://github.com/tyfolino/climkern/assets/13908222/29c77a37-479b-4097-96f8-c21812865090">
 

I think this error is related to the fact that the tutorial data is already a climatological average.

Advice about how to work around this and run the tutorial would be great. Thanks!

**Comment by tyfolino** [comment]
Hi Karen!

I actually already fixed those issues in the "dev" branch of the Python
package. I have to update the tutorial and will upload a new version to
PyPI by Monday. If you can't wait until Monday, you can download the
package from GitHub and install it locally using pip. Otherwise, the fixed
version will be published soon.

Ty

**Comment by kls2177** [comment]
Thanks! Monday is perfect.

**Comment by tyfolino** [comment]
I updated the README with new installation instructions and put the latest release on PyPI. After testing, I no longer encounter the same errors as you. I'm going to close the issue for now, but if you're still having problems, let me know, and I will reopen it!
