### ISSUE TITLE
Spelling Error in Documentation

### ISSUE THREAD

**Issue by kaitlynwen** [tyfolino/climkern#22]
“**linear**” is misspelled on the documentation site in the description for the `method` parameter of `calc_q_feedbacks`

<img width="513" alt="Screenshot 2024-06-24 at 8 56 19 AM" src="https://github.com/tyfolino/climkern/assets/118031472/550b9d5f-2ed2-4429-87dc-43ec76082c59">

**Comment by tyfolino** [comment]
Thanks for catching that, @kaitlynwen ! Would you mind making that correction? The documentation is automatically generated from the function docstrings, so it should be as easy as changing it in the string in the `calc_q_feedbacks` function.
